version: '3'
services:
  nestjs-app:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: my-nest-container
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: ${MONGO_URI}
